### ISSUE TITLE
Consider Changing Class Prefix

### ISSUE THREAD

**Issue by cdstamper** [moltin/ios-sdk#8]
Perhaps for version 2, you should re-consider the two-letter MT prefix. Generally Cocoa apps are encouraged to use a three-letter prefix to avoid clashes with system frameworks.

"Two-letter prefixes like these are reserved by Apple for use in framework classes." from https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html

**Comment by outrunthewolf** [comment]
👍
